package com.citrus.sdk;

/**
 * Created by salil on 9/3/15.
 */
public interface Constants {

    int CVV_LENGTH = 3;
    String INTENT_EXTRA_PAYMENT_PARAMS = "INTENT_EXTRA_PAYMENT_PARAMS";
    String INTENT_EXTRA_NETBANKING_PARAMS = "INTENT_EXTRA_NETBANKING_PARAMS";
    String PARAM_TRANSACTION_RESPONSE = "PARAM_TRANSACTION_RESPONSE";
    String PARAM_SAVED_CARD = "PARAM_SAVED_CARD";
}
